"""
Detection signal functions for Provenance Guard.

Signal 1 (this file, M3): Groq LLM-based semantic classification.
Signal 2 (added in M4): stylometric heuristics.
"""

import json
import os
from groq import Groq

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LLM_SIGNAL_PROMPT = """You are a content attribution analyst. Assess whether the following \
text was written by a human or generated by an AI language model.

Consider: argument structure, specificity of details, natural voice inconsistencies, \
generic phrasing vs. earned specificity, and overall coherence patterns typical of LLM output.

Respond with ONLY a JSON object in this exact format, no other text:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence explanation>"}}

TEXT TO ANALYZE:
{text}
"""


def get_llm_signal(text: str) -> dict:
    """
    Signal 1: asks Groq to estimate the probability the text is AI-generated.

    Returns:
        {"llm_score": float 0.0-1.0, "reasoning": str}
        On failure, returns a safe fallback with llm_score=0.5 (maximally uncertain)
        so a single API hiccup doesn't crash the whole pipeline.
    """
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "user", "content": LLM_SIGNAL_PROMPT.format(text=text)}
            ],
            temperature=0.1,
            max_tokens=200,
        )
        raw = response.choices[0].message.content.strip()

        # Groq sometimes wraps JSON in markdown fences even when told not to.
        if raw.startswith("```"):
            raw = raw.strip("`")
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()

        parsed = json.loads(raw)
        score = float(parsed.get("ai_probability", 0.5))
        score = max(0.0, min(1.0, score))  # clamp to [0,1] in case the model misbehaves

        return {
            "llm_score": score,
            "reasoning": parsed.get("reasoning", ""),
        }

    except Exception as e:
        # Fallback keeps the pipeline alive; log this in production instead of print
        print(f"[signals.get_llm_signal] Groq call failed: {e}")
        return {"llm_score": 0.5, "reasoning": "signal unavailable, defaulted to uncertain"}


if __name__ == "__main__":
    # Quick standalone test — run `python signals.py` to sanity-check the signal
    # before wiring it into the Flask app.
    test_inputs = [
        "The sun dipped below the horizon, painting the sky in hues of amber and rose. "
        "I sat on the porch, coffee in hand, watching the neighborhood slowly go quiet.",

        "Artificial intelligence represents a transformative paradigm shift in modern "
        "society. It is important to note that while the benefits of AI are numerous, "
        "it is equally essential to consider the ethical implications.",

        "ok so i finally tried that new ramen place downtown and honestly? underwhelming. "
        "the broth was fine but they put WAY too much sodium in it.",
    ]

    for i, text in enumerate(test_inputs, 1):
        result = get_llm_signal(text)
        print(f"\n--- Test input {i} ---")
        print(f"Text: {text[:60]}...")
        print(f"llm_score: {result['llm_score']}")
        print(f"reasoning: {result['reasoning']}")